language: java
install: mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: 
#$email and $password as environment variables in travis
- java -cp environment/target/tygronenv-*-jar-with-dependencies.jar login.Login $email $password
- mvn test
jdk:
- oraclejdk8